DBGFLAGS=-ggdb # -fsanitize=address
OPTFLAGS=-O3 -fno-omit-frame-pointer
CFGFLAGS=-std=c++11 -pthread -fno-extern-tls-init -mtls-dialect=gnu2
COMPFLAGS=-fPIC -Wall -Wextra -Wno-unused-function -Wno-unused-parameter

CXXFLAGS=$(DBGFLAGS) $(OPTFLAGS) $(CFGFLAGS) $(COMPFLAGS)

DYNSTACK=0
ifeq ($(DYNSTACK),1)
CXXFLAGS+=-fsplit-stack -DSPLIT_STACK
else
#CXXFLAGS+=-Wstack-usage=2048
endif

