ifeq ($(CC),clang)
CXX=clang++
endif

ifeq ($(shell $(CC) --version|head -1|fgrep -q clang),0)
TLSFLAGS=-fno-extern-tls-init -mtls-dialect=gnu2
endif

DBGFLAGS=-ggdb # -fsanitize=address
OPTFLAGS=-O3 -fno-omit-frame-pointer
CFGFLAGS=-std=c++11 -pthread
COMPFLAGS=-fPIC -Wall -Wextra -Wno-unused-function -Wno-unused-parameter

CXXFLAGS=$(DBGFLAGS) $(OPTFLAGS) $(CFGFLAGS) $(TLSFLAGS) $(COMPFLAGS)

DYNSTACK=0
ifeq ($(DYNSTACK),1)
CXXFLAGS+=-fsplit-stack -DSPLIT_STACK
else
#CXXFLAGS+=-Wstack-usage=2048
endif

